### ISSUE TITLE
patch-user-pod.yaml.tmpl does not quote userAppParams resulting in broken manifest

### ISSUE THREAD

**Issue by sergeyyegournov** [GoogleCloudPlatform/selkies-vdi#11]
[https://github.com/GoogleCloudPlatform/selkies-vdi/blob/bdba31dacee30903d3f45c5b8f2f83ce2d582c62/manifests/brokerapp-base/webrtc-bundle-manifests/patch-user-pod.yaml.tmpl#L74](https://github.com/GoogleCloudPlatform/selkies-vdi/blob/bdba31dacee30903d3f45c5b8f2f83ce2d582c62/manifests/brokerapp-base/webrtc-bundle-manifests/patch-user-pod.yaml.tmpl#L74) does not escape `VDI_` environment variables propagated from userAppParams. We fixed it simply by using `quote`:

```
# Add the userParams to the env prefixed with VDI_
{{- range $key, $value := .UserParams }}
- name: VDI_{{ $key }}
   value: {{ quote $value }} 
{{- end}}
```

**Comment by danisla** [comment]
Thanks for reporting this! Fixed with 260971fc63bd5bdd940976937861474addaadc11
