### ISSUE TITLE
Error "can't evaluate field Type in type pod_broker.AppConfigSpec" in the pod-broker

### ISSUE THREAD

**Issue by nicolopastore** [GoogleCloudPlatform/selkies-vdi#18]
I get the following, in the `pod_broker`, trying to open the App Launcher:
```
error templating file: /var/run/buildsrc/apps/xfce-desktop/jsonpatch-deploy-idle-shutdown.yaml.tmpl: template: jsonpatch-deploy-idle-shutdown.yaml.tmpl:16:18: exe
cuting "jsonpatch-deploy-idle-shutdown.yaml.tmpl" at <.AppSpec.Type>: can't evaluate field Type in type pod_broker.AppConfigSpec
```

**Comment by danisla** [comment]
Please see the resolution for this at the repos new home here: https://github.com/selkies-project/selkies-vdi/issues/2

**Comment by clfmaster** [comment]
thanks @danisla, actually I've fixed the problem using the master branch of selkies.
I suggest you to update the dependencies list in the README file

**Comment by nicolopastore** [comment]
thanks @danisla, actually I've fixed the problem using the master branch of selkies.
I suggest you to update the dependencies list in the README file
